#!/bin/bash

# Jake Gorski
# CS 302 - 1001
# Practicing the use of bash scripts

# SYS
# Check for 'sys' and output request
if [[ "$1" == *sys* ]]
then
	echo "------------------System Information------------------"
	echo -e "Hostname:\t\t $(hostname)"
	echo -e "Uptime:\t\t\t $(uptime | awk '{print $3,$4}' | sed 's/,//')"
	echo -e "Manufacturer:\t\t $(cat /sys/class/dmi/id/chassis_vendor)"
	echo -e "Product Name:\t\t $(cat /sys/class/dmi/id/product_name)"
	echo -e "Version:\t\t $(cat /sys/class/dmi/id/product_version)"
	echo -e "Machine Type:\t\t" `vserver=$(lscpu | grep Hypervisor | wc -l);
       	if [ $vserver -gt 0 ];
       	then
		echo "VM"; 
	else
       		echo "Physical"; 
	fi`
	echo -e "Operating System:\t $(hostnamectl | grep "Operating System" | cut -d ' ' -f5-)"
	echo -e "Kernel:\t\t\t $(uname -r)"
	echo -e "Architecture:\t\t $(arch)"
	echo -e "Processor Name:\t\t $(awk -F':' '/^model name/ {print $2}' /proc/cpuinfo | uniq | sed -e 's/^[ \t]*//')"
	echo -e "Active User:\t\t $(w | cut -d ' ' -f1 | grep -v USER | xargs -n1)"
	echo -e "Main System IP:\t\t $(hostname -I)"

# MEM
# Else check for 'mem' and output request
elif [[ "$1" == *mem* ]]
then
	echo "------------------CPU/Memory Usage------------------"
	echo -e  "$(free)"
	echo -e "Memory Usage:\t" `free | awk '/Mem/{printf("%.2f%%\n"),($3/$2*100)}'`
	echo -e "Swap Usage:\t" `free | awk '/Swap/{printf("%.2f%%\n"),($3/$2*100)}'`
	echo -e "CPU Usage:\t $(cat /proc/stat | awk '/cpu/{printf("%.2f%%\n"), ($2+$4)*100/($2+$4+$5)}' | awk '{print $0}' | head -1)"

# DISK
# Else check for 'disk' and output request
elif [[ "$1" == *disk* ]] 
then
	echo "------------------Disk Usage------------------"
	echo -e "$(df -h | awk '$NF=="/"{printf "Disk Usage: %s\t\t\n\n", $5}')"
	echo ""
	echo -e "$(df -Ph | sed s/%//g | awk '{ if($5 > 80) print $0;}')"


# Else check for no parameters passed
elif [[ "$#" -eq 0 ]]
then
	echo "Usage: sysInfo <sys|mem|disk>"


# Else invalid parameters passed	
else
	echo "Error: Invalid Input"
fi
